name: flutter_mailer
description: Share an email to device Email - Client supports multiple Attachments
version: 2.1.2
homepage:  https://github.com/taljacobson/flutter_mailer

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.9
  path_provider: ^2.0.15
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dataxad.flutter_mailer
        pluginClass: FlutterMailerPlugin
      ios:
        pluginClass: FlutterMailerPlugin

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"
